services:
  postgres:
    image: 'postgres:15'
    container_name: my_postgres
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=12345'
      - 'POSTGRES_USER=myuser'
    ports:
      - 5432:5432
    volumes:
      - ./db-data:/var/lib/postgresql/data

